//COURSES
export const GET_ALL_COURSES = "GET_ALL_COURSES";
export const DELETE_COURSE = 'DELETE_COURSE';

//SHOPPINGCART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";


//SINGIN
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const CHECK_EMAIL_EXISTENCE = 'CHECK_EMAIL_EXISTENCE';
export const CHECK_EMAIL_EXISTENCE_SUCCESS = 'CHECK_EMAIL_EXISTENCE_SUCCESS';
export const CHECK_EMAIL_EXISTENCE_FAILURE = 'CHECK_EMAIL_EXISTENCE_FAILURE';

//USERS
export const DELETE_USER = 'DELETE_USER';
export const GET_USERS = 'GET_USERS';
