//COURSES
export const GET_ALL_COURSES = "GET_ALL_COURSES";

//SHOPPINGCART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

//SINGIN
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const CHECK_EMAIL_EXISTENCE = "CHECK_EMAIL_EXISTENCE";
export const CHECK_EMAIL_EXISTENCE_SUCCESS = "CHECK_EMAIL_EXISTENCE_SUCCESS";
export const CHECK_EMAIL_EXISTENCE_FAILURE = "CHECK_EMAIL_EXISTENCE_FAILURE";

// CATEGORY
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
