//COURSES
export const GET_ALL_COURSES = "GET_ALL_COURSES";
export const SAVE_COURSE='SAVE_COURSE';
//SHOPPINGCART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";


//SINGIN
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const CHECK_EMAIL_EXISTENCE = 'CHECK_EMAIL_EXISTENCE';
export const CHECK_EMAIL_EXISTENCE_SUCCESS = 'CHECK_EMAIL_EXISTENCE_SUCCESS';
export const CHECK_EMAIL_EXISTENCE_FAILURE = 'CHECK_EMAIL_EXISTENCE_FAILURE';

//fILTROS
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE'
export const SET_DEFAULT_FILTERS='SET_DEFAULT_FILTERS';
export const UPDATE_OPTION_FILTERS='UPDATE_OPTION_FILTERS'
export const SORT_BY_NAME= 'SORT_BY_NAME'
export const SET_DATA= 'SET_DATA'
export const FILTER_COURSE_CATEGORY = 'FILTER_COURSE_CATEGORY'
export const FILTER_ORDEN_ALFABETICO = 'FILTER_ORDEN_ALFABETICO'
export const APPLY_FILTER='APPLY_FILTER'
export const SET_OPTION_FILTERS='SET_OPTION_FILTERS'
export const GET_COURSE_FILTER_DEFAULT= 'GET_COURSE_FILTER_DEFAULT'
export const DELETE_FILTERS= 'DELETE_FILTERS'
//CATEGORIAS
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
